
CREATE TABLE docs(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    abstract TEXT
);

CREATE TEMPORARY TABLE temp_json_data (
    json_data TEXT
);

COPY temp_json_data(json_data)
FROM 'C:/Program Files/PostgreSQL/18/data.txt'
WITH (FORMAT csv, QUOTE e'\x01', DELIMITER e'\x02');

INSERT INTO docs(title, abstract)
SELECT
    (json_data::jsonb) ->> 'title',
    (json_data::jsonb) ->> 'abstract'
FROM temp_json_data;

ALTER TABLE docs 
ADD COLUMN title_tsv tsvector,
ADD COLUMN abstract_tsv tsvector;

UPDATE docs 
SET title_tsv =to_tsvector('english', title),
    abstract_tsv= to_tsvector('english',abstract);

CREATE INDEX index_for_title_tsv ON docs USING GIN(title_tsv);
CREATE INDEX index_for_docs_abstract_tsv ON docs USING GIN(abstract_tsv);

SELECT COUNT(*)
FROM docs
WHERE title_tsv @@ to_tsquery('english', 'rat | liver');

SELECT COUNT(*)
FROM docs
WHERE abstract_tsv @@ to_tsquery('english','rat | liver');

SELECT COUNT(*)
FROM docs
WHERE title_tsv @@ to_tsquery('english','rat | liver')
   OR abstract_tsv @@ to_tsquery('english','rat | liver');

SELECT COUNT(*)
FROM docs
WHERE title_tsv @@ to_tsquery('english', 'rat | liver')
  AND abstract_tsv @@ to_tsquery('english','rat | liver');

SELECT COUNT(*)
FROM docs
WHERE title_tsv @@ to_tsquery('english','rat & liver');

SELECT COUNT(*)
FROM docs
WHERE abstract_tsv @@ to_tsquery('english', 'rat & liver');

SELECT COUNT(*)
FROM docs
WHERE title_tsv @@ to_tsquery('english','rat & liver')
   OR abstract_tsv @@ to_tsquery('english','rat & liver');

SELECT COUNT(*)
FROM docs
WHERE title_tsv @@ to_tsquery('english', 'rat & liver')
  AND abstract_tsv @@ to_tsquery('english', 'rat & liver');

SELECT id,title,ts_rank_cd(abstract_tsv, to_tsquery('english', 'cancer & liver')) AS rank
FROM docs
WHERE abstract_tsv @@ to_tsquery('english','cancer & liver')
ORDER BY rank DESC;

SELECT * 
FROM ts_stat(
             'SELECT title_tsv || abstract_tsv FROM docs') 
ORDER BY ndoc DESC
LIMIT 10;

SELECT * 
FROM ts_stat(
    'SELECT title_tsv || abstract_tsv FROM docs'
)
ORDER BY nentry DESC
LIMIT 10;





