# -*- coding: utf-8 -*-
"""ΘΥ-ics23085.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OYou9h4pAau1qesUhX5s-Dtw3ATPpM8M

ΘΕΩΡΙΑ ΥΠΟΛΟΓΙΣΜΟΥ -
Εργασία 1 -
Πετρούλα Τσιμπίνη - ics23085 -
Εξαγωγή πληροφοριών από σελίδες Wikipedia πόλεων
χρησιμοποιώντας κανονικές εκφράσεις
"""

import re
import sys
import requests

#Πρώτα κάνουμε λήψη της σελίδας

def fetch_page(url: str) -> str:
    headers= {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/120.0.0.0 Safari/537.36"
        )
    }
    response =requests.get(url, headers=headers, timeout=15)
    response.raise_for_status()
    return response.text

print("fetch_page()")

# Οι κανονικές εκφράσεις και εξαγωγή των ζητούμενων πεδίων

def extract_city_name(html: str, url: str) -> str:
    #1 Όνομα πόλης, προσπαθούμε να εξαγουμε από: <h1 id="firstHeading">, <title> ή το URL

    #Από τον τίτλο της σελίδας
    m =re.search(
        r'<h1[^>]*id=["\']firstHeading["\'][^>]*>'
        r'(?:<[^>]+>)*([^<]+)(?:<[^>]+>)*</h1>',
        html, re.IGNORECASE
    )
    if m:
        return m.group(1).strip()

    #Από το <title>
    m =re.search(r'<title>([^<|–-]+)', html)
    if m:
        return m.group(1).strip()

    #Από το URL
    m= re.search(r'/wiki/([^#?]+)$', url)
    if m:
        return m.group(1).replace('_', ' ')

    return "Δεν βρέθηκε"

def extract_population(html: str) -> str:
    #2 Πληθυσμός
    #Ψάχνουμε στο infobox για population-related rows.Patterns καλύπτουν: "Population", "population_total".

    patterns =[
        # Μορφή: <td>Population</td><td>325,182</td>
        r'(?i)Population[^<]*</t[dh][^>]*>\s*(?:<[^>]+>\s*)*(\d{1,3}(?:,\d{3})+)',
        # Wikitext: population_total = 325182
        r'(?i)population[_\s]total\s*=\s*([\d,]+)',
        # αριθμός με κόμμα  κοντά σε "Population"
        r'(?i)Population.{0,500}?(\d{1,3}(?:,\d{3}){1,})',
    ]
    for pat in patterns:
        m =re.search(pat, html, re.IGNORECASE | re.DOTALL)
        if m:
            val =m.group(1).strip()
            if re.match(r'^[\d,]+$', val) and len(val) > 3:
                return val
    return "Δεν βρέθηκε"

def extract_area(html: str) -> str:
    #3 Eκταση / Εμβαδό
    #Ψάχνουμε για km², sq mi ή area_total

    patterns = [
        #area_total_km2 ή παρόμοιο στο infobox wikitext
        r'(?i)area[_\s]total[^<]{0,200}?([\d,\.]+)\s*(?:km|sq)',
        # HTML infobox: "Area" label - > αριθμός + μονάδα
        r'(?i)(?:Total area|Area)\s*</[^>]+>\s*(?:<[^>]+>\s*)*([\d,\.]+)\s*(?:km|sq\s*mi)',
        #Κείμενο: αριθμός + km^2
        r'([\d,\.]+)\s*km(?:²|2|&sup2;)',
        # sq mi
        r'([\d,\.]+)\s*sq(?:uare)?\s*mi',
    ]
    for pat in patterns:
        m= re.search(pat, html, re.IGNORECASE | re.DOTALL)
        if m:
            val= m.group(1).strip()
            if re.match(r'^[\d,\.]+$', val):
                return val + " km²"
    return "Δεν βρέθηκε"

def extract_country_region(html: str) -> str:
    #4 Χώρα / Περιφέρεια
    #Ψάχνουμε στο infobox για subdivision_name (χώρα) ή country

    patterns= [
        # subdivision_name1
        r'(?i)subdivision_name\s*=\s*\[\[([^\]|]+)',
        #Από το HTML: "Country" row
        r'(?i)(?:Country|Χώρα)\s*</(?:th|td)[^>]*>\s*(?:<[^>]+>\s*)*([A-ZÀ-Ωa-zα-ω][^<\n]{2,50}?)(?:\s*</|\s*\n)',
        # data-sort-value ή title σε σύνδεσμο χώρας
        r'(?i)(?:country|nation)[^<]{0,100}<a[^>]*title="([^"]{2,50})"',
    ]
    for pat in patterns:
        m= re.search(pat, html, re.IGNORECASE | re.DOTALL)
        if m:
            val =m.group(1).strip()
            # Αποφεύγουμε τιμές με HTML tags
            if '<' not in val and len(val) > 1:
                return val
    return "Δεν βρέθηκε"

def extract_coordinates(html: str) -> str:
    #5 Γεωγραφικές Συντεταγμένες
    #Wikipedia χρησιμοποιεί span.geo ή geo-dec ή data-lat/data-lon

    # span με class="geo" → "lat; lon"
    m= re.search(
        r'<span[^>]*class=["\'][^"\']*\bgeo\b[^"\']*["\'][^>]*>'
        r'\s*([-\d\.]+)\s*;\s*([-\d\.]+)\s*</span>',
        html, re.IGNORECASE
    )
    if m:
        lat = float(m.group(1))
        lon = float(m.group(2))
        lat_dir = "N" if lat >= 0 else "S"
        lon_dir = "E" if lon >= 0 else "W"
        return f"{abs(lat)}°{lat_dir}, {abs(lon)}°{lon_dir}"

    # geo-dec span
    m =re.search(
        r'<span[^>]*class=["\'][^"\']*geo-dec[^"\']*["\'][^>]*>'
        r'\s*([-\d\.]+[°º]?[NS]?\s*[-\d\.]+[°º]?[EW]?)\s*</span>',
        html, re.IGNORECASE
    )
    if m:
        return m.group(1).strip()

    m= re.search(
        r'data-lat=["\']([^"\']+)["\'][^>]*data-lon=["\']([^"\']+)["\']',
        html, re.IGNORECASE
    )
    if m:
        return f"{m.group(1)}, {m.group(2)}"

    m= re.search(
        r'(\d{1,3}[°º]\d{1,2}[′\']\d{0,2}[″"]?\s*[NS]'
        r'\s*\d{1,3}[°º]\d{1,2}[′\']\d{0,2}[″"]?\s*[EW])',
        html
    )
    if m:
        return m.group(1).strip()

    return "Δεν βρέθηκε"

def extract_elevation(html: str) -> str:
  #6 Υψόμετρο
    patterns= [
        r'(?i)elevation[_\s]m\s*=\s*([\d,\.]+)',
        r'(?i)Elevation\s*</[^>]+>\s*(?:<[^>]+>\s*)*([\d,\.]+)\s*(?:m|ft)',
        r'(?i)elevation[^<]{0,100}?([\d,\.]+)\s*m(?:\s|\(|<)',
        #από το infobox HTML απευθείας
        r'(?i)Elevation.*?<td[^>]*>\s*([\d,\.]+)\s*m',
        r'(?i)elevation.*?(\d+)\s*metres',
        r'(?i)elevation.*?(\d+)\s*meters',
    ]
    for pat in patterns:
        m =re.search(pat, html, re.IGNORECASE | re.DOTALL)
        if m:
            val= m.group(1).strip().replace(',', '')
            if re.match(r'^[\d\.]+$', val):
                return val + " m"
    return "Δεν βρέθηκε"

def extract_timezone(html: str) -> str:
  #7 Ζώνη ώρας
    patterns= [
        #Καλύπτουμε UTC+2, UTC-5, UTC−5, UTC±0
        r'(UTC[+\-−–±]\d{1,2}(?::\d{2})?)',
        r'(?i)Time\s*zone[^<]{0,200}(UTC[+\-−–±]\d{1,2}(?::\d{2})?)',
        r'(?i)timezone[^<]{0,200}>\s*([A-Z]{2,5}(?:[+\-]\d)?)\s*<',
    ]
    for pat in patterns:
        m =re.search(pat, html, re.IGNORECASE | re.DOTALL)
        if m:
            return m.group(1).strip()
    return "Δεν βρέθηκε"

def extract_temperatures(html: str) -> dict:
  #8 Μεγιστη, Ελάχιστη και Μέση Θερμοκρασία

    results= {
        "Μέγιστη (°C)":  "Δεν βρέθηκε",
        "Μέση (°C)":     "Δεν βρέθηκε",
        "Ελάχιστη (°C)": "Δεν βρέθηκε",
    }

    # Μέγιστη Θερμοκρασία, ψάχνουμε στον HTML κλιματικό πίνακα
    for pat in [
        r'(?i)record[_\s]high[_\s]c\s*=\s*([-\d\.]+)',
        r'(?i)\bhigh[_\s]c\s*=\s*([-\d\.]+)',
        # HTML climate table: "Record high °C" → αριθμός σε td
        r'(?i)Record\s*high[^<]{0,30}°C.*?<td[^>]*>\s*([-\d\.]+)',
        r'(?i)Record\s*high.*?°C.*?<td[^>]*>([-\d\.]+)',
    ]:
        m= re.search(pat, html, re.DOTALL)
        if m:
            results["Μέγιστη (°C)"] =m.group(1) + " °C"
            break

    #Ελάχιστη Θερμοκρασία
    for pat in [
        r'(?i)record[_\s]low[_\s]c\s*=\s*([-\d\.]+)',
        r'(?i)\blow[_\s]c\s*=\s*([-\d\.]+)',
        r'(?i)Record\s*low[^<]{0,30}°C.*?<td[^>]*>\s*([-\d\.]+)',
        r'(?i)Record\s*low.*?°C.*?<td[^>]*>([-\d\.]+)',
    ]:
        m =re.search(pat, html, re.DOTALL)
        if m:
            results["Ελάχιστη (°C)"] = m.group(1) + " °C"
            break

    #Μέση Θερμοκρασία
    for pat in [
        r'(?i)\bmean[_\s]c\s*=\s*([-\d\.]+)',
        r'(?i)\bavg[_\s]c\s*=\s*([-\d\.]+)',
        r'(?i)Daily\s*mean[^<]{0,30}°C.*?<td[^>]*>\s*([-\d\.]+)',
        r'(?i)(?:Daily mean|Mean temperature).*?°C.*?<td[^>]*>([-\d\.]+)',
    ]:
        m= re.search(pat, html,re.DOTALL)
        if m:
            results["Μέση (°C)"] = m.group(1) + " °C"
            break

    return results

#Το main πρόγραμμα

def print_separator(char="─", width=55):
    print(char*width)


def display_results(url: str, html: str):
    #Εξάγωγή και εκτύπωση όλων των πεδίων
    print_separator("═")
    print(" WIKIPEDIA CITY INFO EXTRACTOR")
    print_separator("═")
    print(f"  URL: {url}")
    print_separator()

    city      = extract_city_name(html, url)
    pop       = extract_population(html)
    area      = extract_area(html)
    country   = extract_country_region(html)
    coords    = extract_coordinates(html)
    elevation = extract_elevation(html)
    timezone  = extract_timezone(html)
    temps     = extract_temperatures(html)

    fields = [
        ("1. Όνομα πόλης",        city),
        ("2. Πληθυσμός",          pop),
        ("3. Έκταση",             area),
        ("4. Χώρα / Περιφέρεια",  country),
        ("5. Συντεταγμένες",      coords),
        ("6. Υψόμετρο",           elevation),
        ("7. Ζώνη ώρας",          timezone),
        ("8α. Μέγιστη θερμοκρασία",     temps["Μέγιστη (°C)"]),
        ("8β. Μέση θερμοκρασία",        temps["Μέση (°C)"]),
        ("8γ. Ελάχιστη θερμοκρασία",    temps["Ελάχιστη (°C)"]),
    ]

    for label, value in fields:
        status = "Success" if value != "Δεν βρέθηκε" else "Failed"
        print(f"  {status}  {label:<26} {value}")

    print_separator("═")

    #Στατιστικά επιτυχίας
    found= sum(1 for _, v in fields if v != "Δεν βρέθηκε")
    total = len(fields)
    pct= round(found / total * 100)
    print(f" Επιτυχής εξαγωγή: {found}/{total} πεδία ({pct}%)")
    print_separator("═")

def main():

    #Είσοδος χρήστη
    try:
        url= input("\n Εισάγετε URL Wikipedia πόλης (π.χ https://en.wikipedia.org/wiki/London):\n >").strip()

        if not url:
            print("Σφάλμα:Δεν δώσατε URL")
            return

        if not url.startswith("http"):
            url= "https://" + url

        html =fetch_page(url)
        display_results(url, html)

    except KeyboardInterrupt:
        print("\n\nΗ διαδικασία διακόπηκε από τον χρήστη")
    except Exception as e:
        print(f"\nΣφάλμα: {e}")

if __name__=="__main__":
    main()