# -*- coding: utf-8 -*-
"""Spark DataFrame API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sumW1LwRhDPRpm2JRa4xo_LMtaRkRhcW

**Spark DataFrame API-ΠΕΤΡΟΥΛΑ ΤΣΙΜΠΙΝΗ-ics23085**
"""

!pip install pyspark

!apt install openjdk-8-jdk

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import FloatType, IntegerType
import time
import shutil

# Initialize Spark Session
spark = (SparkSession.builder
           .appName("Flights-DataFrame-Analysis")
           .master("local[*]")
           .getOrCreate())
sc = spark.sparkContext
print("SparkSession initiated")

from google.colab import files
import io

# 1)Διαβασμα αρχείου

print("\nΠαρακαλώ ανεβάστε το αρχείο flights_2000.csv")
uploaded = files.upload()
filename = next(iter(uploaded.keys()))
print(f"Το αρχείο '{filename}' φορτώθηκε επιτυχώς.")

OUTPUT_DIR = "top_routes_delays.csv"

# 1) Διαβασμα του flights_2000.csv ως DataFrame με Spark.

df = (spark.read.csv(filename, header=True, inferSchema=True)
      # Ασφαλής μετατροπή τύπων
      .withColumn("DEP_DELAY", F.col("DEP_DELAY").cast(FloatType()))
      .withColumn("CANCELLED", F.col("CANCELLED").cast(IntegerType()))
     )

# 2) Εμφανιση το schema του πίνακα με printSchema()
print("\n--- DataFrame Schema ---")
df.printSchema()

# 3) Φιλτράρετε τις εγγραφές και υπολογίστε

# Φιλτράρισμα και καθαρισμός
filtered_df = (df
               .filter(F.col("CANCELLED") == 0)
               .na.drop(subset=["DEP_DELAY"])
              )

# Δημιουργία της διαδρομής route ως μοναδικό πεδίο
routes_df = filtered_df.withColumn(
    "ROUTE",
    F.concat(F.col("ORIGIN_AIRPORT"), F.lit("-"), F.col("DEST_AIRPORT"))
)

# Υπολογισμός και τop-10
avg_delay_df = (routes_df
                .groupBy("ROUTE")
                .agg(F.avg("DEP_DELAY").alias("AvgDelay"))
                .orderBy(F.desc("AvgDelay"))
                .limit(10)
               )

# 5) Εκτέλεση και χρονομέτρηση (5 επαναλήψεις)

execution_times = []
first_action_times = []
last_results = None

print("\n--- Εκτέλεση DataFrame API (5 επαναλήψεις) ---")

for i in range(5):
    print(f"\n--- Εκτέλεση {i+1}/5 ---")

    # Χρονομέτρηση "πρώτου action": count()
    start_first_action = time.time()
    count_action = filtered_df.count()
    end_first_action = time.time()
    first_action_time = end_first_action - start_first_action
    first_action_times.append(first_action_time)
    print(f"Χρόνος Πρώτου Action (count): {first_action_time:.4f} δευτ.")

    # Χρονομέτρηση "συνολικού χρόνου", τελική Action (collect) για το top-10
    start_total = time.time()
    final_results = avg_delay_df.collect()
    end_total = time.time()
    total_time = end_total - start_total
    execution_times.append(total_time)
    last_results = final_results
    print(f"Συνολικός Χρόνος Εκτέλεσης (collect Top-10): {total_time:.4f} δευτ.")

# 4) Αποθηκεύστε το αποτέλεσμα σε αρχείο CSV με write.csv()

# Αφαίρεση προηγούμενης εξόδου (αν υπάρχει)
try:
    shutil.rmtree(OUTPUT_DIR)
    print(f"\nΑφαιρέθηκε ο προηγούμενος φάκελος {OUTPUT_DIR}/")
except FileNotFoundError:
    pass

# Αποθήκευση του DataFrame
avg_delay_df.write.csv(OUTPUT_DIR, header=True, mode="overwrite")
print(f"Τα Top-10 Routes αποθηκεύτηκαν επιτυχώς στον φάκελο: {OUTPUT_DIR}/")

# 5.a,b,c) Υπολογισμοί και εκτύπωση Αποτελεσμάτων

print("\n--- Αποτελέσματα Χρονομέτρησης & Υπολογισμοί (DataFrame API) ---")

# Ταξινόμηση και εύρεση των ενδιάμεσων 3 τιμών
sorted_total = sorted(execution_times)
sorted_first_action = sorted(first_action_times)

intermediate_total = sorted_total[1:-1]
intermediate_first_action = sorted_first_action[1:-1]

avg_total_time = sum(intermediate_total) / len(intermediate_total)
avg_first_action_time = sum(intermediate_first_action) / len(intermediate_first_action)

print("\n   Δείγμα Εξόδου (Top-10 Routes)")
print("| Route | Μέση Καθυστέρηση (λεπτά) |")
print("|:------|:-------------------------|")
for row in last_results:
    print(f"| {row.ROUTE} | {row.AvgDelay:.2f} |")
print("---------------------------------------")

print("\n    Πίνακας Χρόνων Εκτέλεσης (DataFrame API)")
print("| Εκτέλεση | Συνολικός Χρόνος (sec) | Χρόνος Πρώτου Action (sec) |")
print("|:---------|:-----------------------|:--------------------------|")
for i in range(5):
    print(f"| {i+1} | {execution_times[i]:.4f} | {first_action_times[i]:.4f} |")

print("\n--- Μέσοι Χρόνοι (3 ενδιάμεσες εκτελέσεις) ---")
print(f"| **Μέσος Συνολικός Χρόνος** | **{avg_total_time:.4f} sec** |")
print(f"| **Μέσος Χρόνος Πρώτου Action** | **{avg_first_action_time:.4f} sec** |")

# ΘΕΜΑ 4: Οπτικοποίηση αποτελεσμάτων

import pandas as pd
import matplotlib.pyplot as plt

# 1) Μετατροπή του τελικού spark dataframe σε pandas dataframe
# Χρησιμοποιούμε το 'avg_delay_df' που υπολογίστηκε στο θέμα 2
pandas_df = avg_delay_df.toPandas()

# Ταξινομούμε εκ νέου το pandas dataframe σε αύξουσα σειρά AvgDelay
# Αυτό είναι απαραίτητο για να εμφανιστεί η μεγαλύτερη τιμή στην κορυφή του οριζόντιου γραφήματος
pandas_df = pandas_df.sort_values('AvgDelay', ascending=True)

# 2,3) Δημιουργία και εμφάνιση οριζόντιου γραφήματος
plt.figure(figsize=(12, 8))
plt.barh(pandas_df['ROUTE'], pandas_df['AvgDelay'], color='#1f77b4')

# Προσθήκη τίτλων και ετικετών
plt.xlabel("Μέση Καθυστέρηση Αναχώρησης (λεπτά)", fontsize=14)
plt.ylabel("Διαδρομή (ORIGIN-DESTINATION)", fontsize=14)
plt.title("Top-10 Διαδρομές με τη Μεγαλύτερη Μέση Καθυστέρηση Αναχώρησης (DataFrame API)", fontsize=16)

# Εμφάνιση των τιμών πάνω στις ράβδους για καλύτερη ανάγνωση
for index, value in enumerate(pandas_df['AvgDelay']):
    plt.text(value, index, f' {value:.2f}', va='center')

plt.grid(axis='x', linestyle='--', alpha=0.6) # Εμφάνιση οριζόντιων γραμμών
plt.tight_layout() # Προσαρμογή διάταξης για να χωράνε οι ετικέτες
plt.show()

print("Το γράφημα απεικονίζει τις Top-10 διαδρομές πτήσεων με τη μεγαλύτερη μέση καθυστέρηση αναχώρησης.")

# ΘΕΜΑ 5
from pyspark.sql.types import FloatType, IntegerType
import seaborn as sns

# α. Δημιουργία της στήλης ωρα αναχώρησης (HOUR)
# Η SCHED_DEP είναι σε μορφή YYYY-MM-DD HH:MM οπότε παίρνουμε τις 2 ψηφιακές τιμές μετά τη θέση 11
# Το substr(12, 2) παίρνει τις ώρες (πχ από '2025-10-09 18:40' παίρνει '18')
df_with_hour = filtered_df.withColumn(
    "HOUR",
    F.substring(F.col("SCHED_DEP"), 12, 2).cast(IntegerType())
)

# Υπολογισμός μέσης καθυστέρησης ανά ωρα
avg_delay_by_hour = df_with_hour.groupBy("HOUR").agg(
    F.avg("DEP_DELAY").alias("AvgDelay")
).orderBy("HOUR")

# Μετατροπή σε pandas Dataframe για εύκολη οπτικοποίηση
pandas_df = avg_delay_by_hour.toPandas()

# Μετατροπή της στήλης 'HOUR' σε ακέραιο τύπο στο pandas Dataframe
pandas_df['HOUR'] = pandas_df['HOUR'].astype(int)

# Δημιουργία οπτικοποίησης
plt.figure(figsize=(12, 6))
sns.barplot(x="HOUR", y="AvgDelay", data=pandas_df, palette="viridis")
plt.title('Μέση Καθυστέρηση Αναχώρησης ανά Ώρα της Ημέρας')
plt.xlabel('Ώρα Αναχώρησης (24ωρο)')
plt.ylabel('Μέση Καθυστέρηση (λεπτά)')
plt.xticks(rotation=0)
plt.grid(axis='y', linestyle='--')
plt.show()

# Εκτύπωση πίνακα αποτελεσμάτων
print("\n Πίνακας: Μέση Καθυστέρηση ανά Ώρα Αναχώρησης")
print("| Ώρα | Μέση Καθυστέρηση (λεπτά) |")
print("|:---:|:------------------------:|")
for index, row in pandas_df.iterrows():
    print(f"| {int(row['HOUR']):02d}:00 | {row['AvgDelay']:.2f} |")
print("-----------------------------------")

# β.Υπολογισμός μέσης καθυστέρησης και πλήθους πτήσεων ανά AIRLINE
airline_delay_analysis = filtered_df.groupBy("AIRLINE").agg(
    F.count("*").alias("FlightCount"),
    F.avg("DEP_DELAY").alias("AvgDelay")
).orderBy(F.col("AvgDelay").desc()) # Ταξινόμηση κατά φθίνουσα μέση καθυστέρηση

#Συλλογή αποτελεσμάτων και μετατροπή σε Pandas datafame για οπτικοποίηση
pandas_df_airline = airline_delay_analysis.toPandas()

# Δημιουργία oπτικοποίησης
plt.figure(figsize=(10, 7))
sns.barplot(
    x="AIRLINE",
    y="AvgDelay",
    data=pandas_df_airline,
    hue="AIRLINE",
    palette="coolwarm",
    legend=False
)

plt.title('Μέση Καθυστέρηση Αναχώρησης ανά Αεροπορική Εταιρεία')
plt.xlabel('Κωδικός Αεροπορικής Εταιρείας (AIRLINE)')
plt.ylabel('Μέση Καθυστέρηση (λεπτά)')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--')
plt.tight_layout()
plt.show()

# 5. Εκτύπωση πίνακα αποτελεσμάτων
print("\n Πίνακας: Μέση Καθυστέρηση και Πλήθος Πτήσεων ανά Αεροπορική Εταιρεία")
print("| AIRLINE | Πλήθος Πτήσεων | Μέση Καθυστέρηση (λεπτά) |")
print("|:-------:|:---------------:|:------------------------:|")
for index, row in pandas_df_airline.iterrows():
    print(f"| {row['AIRLINE']} | {row['FlightCount']:,} | {row['AvgDelay']:.2f} |")
print("---------------------------------------------------------")

# γ.Δημιουργία της στήλης ROUTE και υπολογισμός μεσης καθυστέρησης
df_with_route = filtered_df.withColumn(
    "ROUTE",
    F.concat(F.col("ORIGIN_AIRPORT"), F.lit("->"), F.col("DEST_AIRPORT"))
)

route_delay_analysis = df_with_route.groupBy("ROUTE", "ORIGIN_AIRPORT", "DEST_AIRPORT").agg(
    F.count("*").alias("FlightCount"),
    F.avg("DEP_DELAY").alias("AvgDelay")
)

# Εντοπισμός των πιο συχνών διαδρομών για την οπτικοποίηση
# Περιορίζουμε στις 10 πιο συχνές διαδρομές
top_n = 10
top_routes_df = route_delay_analysis.orderBy(F.col("FlightCount").desc()).limit(top_n)

#Συλλογή αποτελεσμάτων και μετατροπή σε Pandas DataFrame
# Μόνο για τις top N διαδρομές
pandas_df_routes = top_routes_df.toPandas()

#Αναδιαμόρφωση για Heatmap χρειάζεται pivot table (Origin Airport vs Dest Airport)
heatmap_data = pandas_df_routes.pivot_table(
    index='ORIGIN_AIRPORT',
    columns='DEST_AIRPORT',
    values='AvgDelay',
    fill_value=0 # Βάζουμε 0 καθυστέρηση όπου δεν υπάρχει διαδρομή στο top-10
)

#Δημιουργία οπτικοποίησης (Heatmap)
plt.figure(figsize=(10, 8))
sns.heatmap(
    heatmap_data,
    annot=True,
    fmt=".1f",
    cmap="YlOrRd", # Χρωμα από κίτρινο/πορτοκαλί σε κόκκινο (χαμηλή σε υψηλή καθυστέρηση)
    linewidths=.5,
    linecolor='black',
    cbar_kws={'label': 'Μέση Καθυστέρηση Αναχώρησης (λεπτά)'}
)

plt.title(f'Heatmap Μέσης Καθυστέρησης ({top_n} Πιο Συχνές Διαδρομές)')
plt.xlabel('Αεροδρόμιο Προορισμού (DEST_AIRPORT)')
plt.ylabel('Αεροδρόμιο Αναχώρησης (ORIGIN_AIRPORT)')
plt.tight_layout()
plt.show()

# 6) Καθάρισμα
spark.stop()
print("\nSpark session ended")