# -*- coding: utf-8 -*-
"""Spark RDD API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eq9iNpSlAqdg2e4Y3SFxfiKzFpKLiWVv

**Spark RDD API-ΠΕΤΡΟΥΛΑ ΤΣΙΜΠΙΝΗ-ICS23085**
"""

# 1)Εγκατάσταση και Εκκίνηση του Spark

!pip -q install pyspark

from pyspark.sql import SparkSession
import time
import csv
from io import StringIO

# Εκκινηση Spark Session
spark = (SparkSession.builder
           .appName("Flights-RDD-Analysis")
           .master("local[*]")
           .getOrCreate())
sc = spark.sparkContext
print("Spark session started")

from google.colab import files
uploaded = files.upload()

FILE_NAME = "flights_2000.csv"

#2)Διάβασμα αρχείου flights_2000.csv ως text RDD και split/parse.

# Χρησιμοποιούμε sc.textFile() για να διαβασουμε το αρχειο ως RDD από γραμμές κειμένου.
# Η πρώτη γραμμη είναι το header και πρεπει να εξαιρεθεί.
raw_rdd = sc.textFile(FILE_NAME)
header = raw_rdd.first()
data_rdd = raw_rdd.filter(lambda line: line != header)

# Συνάρτηση parsing για να διαχωρισουμε τα πεδια μιας γραμμης.
def parse_line(line):
    # Χρησιμοποιούμε StringIO για να το διαβάσει σαν αρχείο ο csv reader
    reader = csv.reader(StringIO(line))
    row = next(reader)

    try:
        #ORIGIN_AIRPORT (4ο πεδίο, index 3)
        origin_airport = row[3].strip()
        # DEP_DELAY (7ο πεδίο, index 6). Μετατροπή σε float, αν δεν είναι κενό.
        dep_delay_str = row[6].strip()
        dep_delay = float(dep_delay_str) if dep_delay_str else None
        #CANCELLED (11ο πεδίο, index 10)
        cancelled = int(row[10].strip())
        return (origin_airport, dep_delay, cancelled)
    except (IndexError, ValueError):
        #Επιστρέφουμε None αν η γραμμή είναι κατεστραμμένη ή αν λείπουν πεδία
        return None

# Parsed RDD με φιλτράρισμα των γραμμών που δεν έγιναν parse σωστά none
parsed_rdd = data_rdd.map(parse_line).filter(lambda x: x is not None)

# Φιλτράρισμα,εξαίρεση ακυρωμένων πτήσεων CANCELLED == 1
# και πτήσεων που δεν έχουν καθυστέρηση αναχώρησης DEP_DELAY is None
filtered_rdd = parsed_rdd.filter(lambda x: x[2] == 0 and x[1] is not None)

# 3)Εξαγωγή ζευγών (origin_airport, delay_minutes)
# Χρησιμοποιούμε map() για να εξαγάγουμε τα ζεύγη (origin_airport, dep_delay)
pairs_rdd = filtered_rdd.map(lambda x: (x[0], x[1]))

# 4) Υπολογίστε μέση καθυστέρηση ανά αεροδρόμιο αναχώρησης με combineByKey

#(άθροισμα καθυστερήσεων, πλήθος πτήσεων)->(sum, count)

# Συνάρτηση δημιουργίας για αρχικοποιηση του accumulator για ένα νέο κλειδί
def create_comb(delay):
    return (delay, 1)

# Συνάρτηση συγχώνευσης τιμής ,ενημερώνει τον accumulator με μια νέα τιμή
def merge_val(acc, delay):
    return (acc[0] + delay, acc[1] + 1)

# Συνάρτηση συγχώνευσης accumulators,συγχωνεύει δύο accumulators
def merge_comb(acc1, acc2):
    return (acc1[0] + acc2[0], acc1[1] + acc2[1])

# Εφαρμογή combineByKey για τον υπολογισμό του (sum, count) ανά αεροδρόμιο
sum_count_rdd = pairs_rdd.combineByKey(create_comb, merge_val, merge_comb)

# Υπολογισμός της μέσης καθυστέρησης (sum/count)
avg_delay_rdd = sum_count_rdd.mapValues(lambda acc: acc[0] / acc[1])

# 5) Επιστρέψτε top-10 αεροδρόμια με μεγαλύτερη μέση καθυστέρηση (descending)

#Μετατροπή σε (μέση καθυστέρηση,αεροδρόμιο) για να κάνουμε ταξινόμηση
sorted_rdd = avg_delay_rdd.map(lambda x: (x[1], x[0]))

#Ταξινόμηση σε φθίνουσα σειρά και επιλογή των top 10
top_10_results = sorted_rdd.sortByKey(ascending=False).take(10)

#Διαδικασία εκτέλεσης και χρονομέτρησης

execution_times = []
first_action_times = []

for i in range(5):
    print(f"\n--- Εκτέλεση {i+1}/5 ---")

 # 6) Εκτελεση και χρονομετρηση

    # Χρονομετρηση "πρώτου action" (όταν το Spark ξεκινάει πραγματικά)
    start_first_action = time.time()
    # Ένα απλό action πριν το τελικό collect
    count_action = avg_delay_rdd.count()
    end_first_action = time.time()
    first_action_time = end_first_action - start_first_action
    first_action_times.append(first_action_time)
    print(f"Πρώτο Action (count) ολοκληρώθηκε. Χρόνος: {first_action_time:.4f} δευτ.")

    # Χρονομέτρηση "συνολικού χρόνου" (συμπεριλαμβανομένου του τελικού collect)
    start_total = time.time()
    # Τελικό action->υπολογισμός και επιστροφή των top-10
    final_results = sorted_rdd.sortByKey(ascending=False).take(10)
    end_total = time.time()
    total_time = end_total - start_total
    execution_times.append(total_time)
    print(f"Συνολικός Χρόνος Εκτέλεσης (Top-10): {total_time:.4f} δευτ.")

#Υπολογισμός Μέσων Όρων

print("\n--- Αποτελέσματα Χρονομέτρησης & Υπολογισμοί ---")

# Ταξινόμηση και εύρεση των ενδιάμεσων 3 τιμών
sorted_total = sorted(execution_times)
sorted_first_action = sorted(first_action_times)

#Οι 3 ενδιάμεσες τιμές (αφαιρούμε τη μεγαλύτερη και τη μικρότερη)
intermediate_total = sorted_total[1:-1]
intermediate_first_action = sorted_first_action[1:-1]

# Υπολογισμός μέσου όρου
avg_total_time = sum(intermediate_total) / len(intermediate_total)
avg_first_action_time = sum(intermediate_first_action) / len(intermediate_first_action)

# Εκτύπωση Αποτελεσμάτων

print("\n Πίνακας Αποτελεσμάτων (RDD API)")
print("| Αεροδρόμιο | Μέση Καθυστέρηση (λεπτά) |")
print("|:-----------|:-------------------------|")
for delay, airport in final_results:
    print(f"| {airport} | {delay:.2f} |")
print("---------------------------------------")

print("\n Πίνακας Χρόνων Εκτέλεσης")
print("| Εκτέλεση | Συνολικός Χρόνος (sec) | Χρόνος Πρώτου Action (sec) |")
print("|:---------|:-----------------------|:--------------------------|")
for i in range(5):
    print(f"| {i+1} | {execution_times[i]:.4f} | {first_action_times[i]:.4f} |")

print("\n--- Μέσοι Χρόνοι ---")
print(f"| **Μέσος Συνολικός Χρόνος** | **{avg_total_time:.4f} sec** |")
print(f"| **Μέσος Χρόνος Πρώτου Action** | **{avg_first_action_time:.4f} sec** |")

# 7) Καθάρισμα
spark.stop()
print("\nSpark session ended")